version: '3'

services:
  db:
    container_name: "e-reservation-postgres"
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: platzi
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
    - ./data:/var/lib/postgresql/data


  e-reservation:
    container_name: "e-reservation-app"
    build: .
    ports:
      - "8091:8080"
    links:
      - db
